entrypoint: bundle exec rails server Puma -p $PORT
env: flex
runtime: ruby

env_variables:
  SECRET_KEY_BASE: 315d3cf84e9bd9e0512b8278152719feee04c50d7ea01d4f0e6f41c68da802f0e576d53a8c46f6f7b6e3cdc3685c310bfb6685a93864099f018d1b4f75a0a577

manual_scaling:
  instances: 1

beta_settings:
  cloud_sql_instances: babelon-madhacks:us-central1:babelon-madhacks-postgres
